#include <gtest/gtest.h>

extern "C" {
#include "task.h"
#define TASK_REQ(NAME) NAME##_REQ
#define TASK_RESP(NAME) NAME##_RESP
}

TEST(TaskTest, TaskID) {
  EXPECT_EQ(TASK_REQ(GET_OR_INSERT) + 127, TASK_RESP(GET_OR_INSERT));
  EXPECT_EQ(TASK_REQ(GET_POINTER) + 127, TASK_RESP(GET_POINTER));
  EXPECT_EQ(TASK_REQ(UPDATE_POINTER) + 127, TASK_RESP(UPDATE_POINTER));
  EXPECT_EQ(TASK_REQ(GET_MAX_LINK_SIZE) + 127, TASK_RESP(GET_MAX_LINK_SIZE));
  EXPECT_EQ(TASK_REQ(FETCH_MAX_LINK) + 127, TASK_RESP(FETCH_MAX_LINK));
  EXPECT_EQ(TASK_REQ(MERGE_MAX_LINK) + 127, TASK_RESP(MERGE_MAX_LINK));
  EXPECT_EQ(TASK_REQ(NEW_MAX_LINK) + 127, TASK_RESP(NEW_MAX_LINK));
}

TEST(TaskTest, RespTaskType) {
  EXPECT_EQ(RespTaskType(SET_DPU_ID_REQ), EMPTY_RESP);
  EXPECT_EQ(RespTaskType(CREATE_INDEX_REQ), EMPTY_RESP);
  EXPECT_EQ(RespTaskType(TASK_REQ(GET_OR_INSERT)), TASK_RESP(GET_OR_INSERT));
  EXPECT_EQ(RespTaskType(TASK_REQ(GET_POINTER)), TASK_RESP(GET_POINTER));
  EXPECT_EQ(RespTaskType(TASK_REQ(UPDATE_POINTER)), TASK_RESP(UPDATE_POINTER));
  EXPECT_EQ(RespTaskType(TASK_REQ(GET_MAX_LINK_SIZE)),
            TASK_RESP(GET_MAX_LINK_SIZE));
  EXPECT_EQ(RespTaskType(TASK_REQ(FETCH_MAX_LINK)), TASK_RESP(FETCH_MAX_LINK));
  EXPECT_EQ(RespTaskType(TASK_REQ(MERGE_MAX_LINK)), TASK_RESP(MERGE_MAX_LINK));
  EXPECT_EQ(RespTaskType(TASK_REQ(NEW_MAX_LINK)), TASK_RESP(NEW_MAX_LINK));
}

TEST(TaskTest, IsVarLenTask) {
  EXPECT_EQ(IsVarLenTask(TASK_REQ(GET_OR_INSERT)), true);
  EXPECT_EQ(IsVarLenTask(TASK_REQ(GET_POINTER)), true);
  EXPECT_EQ(IsVarLenTask(TASK_RESP(FETCH_MAX_LINK)), true);
  EXPECT_EQ(IsVarLenTask(TASK_REQ(MERGE_MAX_LINK)), true);
  EXPECT_EQ(IsVarLenTask(TASK_REQ(NEW_MAX_LINK)), true);
}